### ISSUE TITLE
Class `Predict` parameter error and repeated instantiation in `main.py`.

### ISSUE THREAD

**Issue by heegreis** [fastyangmh/ImageClassification#1]
Why `Predict` repeated instantiation?
https://github.com/fastyangmh/ImageClassification/blob/483e6f8e9131b7a172696d3488036843f0abf5ec/main.py#L21-L23
Maybe edit as following:
```python
        predicter = Predict(project_parameters=project_parameters)
        result = predicter.predict(filepath=project_parameters.root)
```
and the  parameter `filepath` when call `Predict.predict` is not match to the definition `inputs`.
https://github.com/fastyangmh/ImageClassification/blob/483e6f8e9131b7a172696d3488036843f0abf5ec/src/predict.py#L30

**Comment by fastyangmh** [comment]
@Heegreis, I solved the problem, please confirm the PR. If there is no problem, I will merge to the dev branch. Thank you.
